'use client';

import { InlineMath, BlockMath } from 'react-katex'; // Keep imports
import { useState, ChangeEvent } from 'react'; // Removed useMemo
import QuizQuestion from '@/components/QuizQuestion'; // Assuming this component exists
import 'katex/dist/katex.min.css';

// --- Type Definitions ---
interface YouTubeEmbedProps {
  videoId: string;
  title: string;
}

interface MiniCheckQuestionProps {
  question: string;
  correctAnswer: string;
  explanation: string;
}

// !! Adjust based on your actual QuizQuestion component !!
interface QuizQuestionProps {
    key: number;
    // questionNumber?: number; // Make optional or ensure component accepts it
    question: string;
    options: string[];
    correctAnswer: number;
    hint: string;
    selectedAnswer: number | null;
    showResults: boolean;
    onSelectAnswer: (answerIndex: number) => void;
}

// --- Reusable Components (Styled as per design system) ---

// YouTube Embed Component
function YouTubeEmbed({ videoId, title }: YouTubeEmbedProps) {
  return (
    <div className="my-4">
      <p className="mb-2 font-semibold font-inter text-dark-gray dark:text-light-gray">{title}:</p>
      <div className="aspect-w-16 aspect-h-9 rounded-lg overflow-hidden shadow-md">
         <iframe
           className="w-full h-full"
           src={`https://www.youtube.com/embed/${videoId}`}
           title={title}
           frameBorder="0"
           allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
           allowFullScreen>
         </iframe>
      </div>
    </div>
  );
}

// Mini Interactive Question Component
function MiniCheckQuestion({ question, correctAnswer, explanation }: MiniCheckQuestionProps) {
  const [revealed, setRevealed] = useState(false);
  return (
    <div className="mt-6 p-4 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 shadow-md">
      <p className="font-medium text-sm mb-2 font-inter text-dark-gray dark:text-light-gray">{question}</p>
      {!revealed && (
        <button
          onClick={() => setRevealed(true)}
          className="text-xs bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-inter font-semibold py-1 px-3 rounded transition-colors"
        >
          Check Answer
        </button>
      )}
      {revealed && (
        <div className="text-sm space-y-1 font-inter">
          <p className="text-dark-gray dark:text-light-gray"><strong className="text-teal dark:text-mint">Answer:</strong> {correctAnswer}</p>
          <p className="text-dark-gray dark:text-light-gray"><strong className="text-gray-600 dark:text-gray-400">Explanation:</strong> {explanation}</p>
           <button
            onClick={() => setRevealed(false)}
            className="text-xs text-blue-600 dark:text-blue-400 hover:underline mt-1 font-inter"
          >
            Hide
          </button>
        </div>
      )}
    </div>
  );
}


// --- Page Specific Data ---
const quizQuestions = [
  {
    "question": "What is the primary electrical characteristic of a diode?",
    "options": [
      "It amplifies current.",
      "It allows current to flow easily in only one direction.", // Correct
      "It stores electric charge.",
      "It has constant resistance regardless of voltage."
    ],
    "correctAnswer": 1,
    "hint": "Diodes act like a one-way street for electrical current."
  },
  {
    "question": "A standard semiconductor diode is formed by joining which two types of materials?",
    "options": [
      "A conductor and an insulator",
      "An N-type semiconductor and a P-type semiconductor", // Correct
      "Two N-type semiconductors",
      "Two P-type semiconductors"
    ],
    "correctAnswer": 1,
    "hint": "The junction between P-type and N-type material creates the diode's unique properties."
  },
  {
    "question": "What is the 'depletion region' in a P-N junction?",
    "options": [
      "A region with very high conductivity.",
      "A region near the junction depleted of free charge carriers (electrons and holes).", // Correct
      "The physical connection point between P and N layers.",
      "The area where electrons are generated."
    ],
    "correctAnswer": 1,
    "hint": "Diffusion and recombination of electrons and holes near the junction create this region."
  },
  {
    "question": "What does the 'barrier potential' (or built-in voltage) of a diode represent?",
    "options": [
      "The voltage required to destroy the diode.",
      "The voltage naturally present across the depletion region due to fixed ions.", // Correct
      "The maximum voltage the diode can block.",
      "The voltage generated by the diode."
    ],
    "correctAnswer": 1,
    "hint": "This potential opposes further diffusion of charge carriers across the junction."
  },
  {
    "question": "Connecting the positive terminal of a voltage source to the P-side and the negative terminal to the N-side of a diode is called:",
    "options": [
      "Reverse biasing",
      "Forward biasing", // Correct
      "Zero biasing",
      "Breakdown biasing"
    ],
    "correctAnswer": 1,
    "hint": "This configuration reduces the barrier potential and allows current to flow."
  },
  {
    "question": "What happens to the depletion region width when a diode is forward biased?",
    "options": [
      "It widens significantly.",
      "It narrows.", // Correct
      "It remains unchanged.",
      "It disappears instantly."
    ],
    "correctAnswer": 1,
    "hint": "The applied forward voltage opposes the barrier potential, shrinking the depletion region."
  },
   {
    "question": "What happens to the depletion region width when a diode is reverse biased?",
    "options": [
      "It narrows significantly.",
      "It widens.", // Correct
      "It remains unchanged.",
      "It fills with charge carriers."
    ],
    "correctAnswer": 1,
    "hint": "The applied reverse voltage adds to the barrier potential, pushing carriers away and widening the region."
  },
  {
    "question": "The 'cut-in voltage' (approx. 0.7V for Silicon, 0.3V for Germanium) is the forward bias voltage at which:",
    "options": [
      "The diode breaks down.",
      "The reverse current starts.",
      "Significant forward current begins to flow.", // Correct
      "The depletion region is largest."
    ],
    "correctAnswer": 2,
    "hint": "Below this voltage, very little current flows even in forward bias."
  },
   {
    "question": "What typically happens if the reverse bias voltage applied to a diode exceeds its 'breakdown voltage'?",
    "options": [
      "The diode becomes a perfect conductor.",
      "The diode safely turns off.",
      "A large reverse current flows, potentially damaging the diode.", // Correct
      "The diode starts emitting light."
    ],
    "correctAnswer": 2,
    "hint": "Breakdown means the insulating property in reverse bias fails, leading to high current."
  },
  {
    "question": "What is the purpose of adding a resistor in series with an LED (a type of diode)?",
    "options": [
      "To increase the light output.",
      "To change the color of the light.",
      "To limit the forward current and prevent the LED from burning out.", // Correct
      "To store energy for the LED."
    ],
    "correctAnswer": 2,
    "hint": "Once forward biased above its cut-in voltage, a diode's resistance is very low; the resistor controls the current."
  }
];


// --- KaTeX String Constants ---
const katex_Si = 'Si';
const katex_Ge = 'Ge';
const katex_GaAs = 'GaAs';
const katex_PN = 'P-N';
const katex_V_barrier_Si = '0.7V';
const katex_V_barrier_Ge = '0.3V';
const katex_IV = 'I-V';

// --- Main Page Component ---
const DiodesPage = () => { // Renamed component
  // --- State Variables ---
  const [showQuiz, setShowQuiz] = useState(false);
  const [selectedAnswers, setSelectedAnswers] = useState<(number | null)[]>(new Array(quizQuestions.length).fill(null));
  const [showResults, setShowResults] = useState(false);
  const [score, setScore] = useState(0);

  // --- Quiz Handlers ---
  const handleAnswerSelect = (questionIndex: number, answerIndex: number) => {
    if (showResults) return;
    const newSelectedAnswers = [...selectedAnswers];
    newSelectedAnswers[questionIndex] = answerIndex;
    setSelectedAnswers(newSelectedAnswers);
  };

  const handleSubmit = () => {
    const correctCount = selectedAnswers.reduce((count: number, answer: number | null, index: number) => {
      if (answer === null) return count;
      return count + (answer === quizQuestions[index].correctAnswer ? 1 : 0);
    }, 0);
    setScore(correctCount);
    setShowResults(true);
  };

  const resetQuiz = () => {
    setShowQuiz(false);
    setShowResults(false);
    setSelectedAnswers(new Array(quizQuestions.length).fill(null));
    setScore(0);
  }

  // --- Component Render ---
   return (
    <div className="bg-off-white text-dark-gray dark:bg-deep-navy dark:text-light-gray min-h-screen font-lora">
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-16 py-8">
            <h1 className="text-4xl lg:text-5xl font-bold font-playfair mb-8 lg:mb-12 text-center">
                5.2 Diodes and Their Functions {/* Updated Title */}
            </h1>

            <div className="grid grid-cols-1 lg:grid-cols-12 lg:gap-x-12">
                {/* Left Column */}
                <article className="lg:col-span-7 space-y-6">

                    {/* Introduction to Diodes */}
                    <section>
                         <h2 className="text-3xl font-semibold font-playfair mt-6 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             What is a Diode?
                         </h2>
                         <p className="leading-relaxed">
                            A <strong className="text-teal dark:text-teal font-semibold">diode</strong> is a fundamental two-terminal electronic component with a unique characteristic: it allows electric current to flow easily in one direction but strongly resists current flow in the opposite direction. Think of it as an electrical one-way valve.
                         </p>
                         <p className="mt-3 leading-relaxed">
                            While various types exist, the most common are <strong className="text-teal dark:text-teal font-semibold">semiconductor diodes</strong>, typically made from silicon (<InlineMath math={katex_Si}/>), germanium (<InlineMath math={katex_Ge}/>), or gallium arsenide (<InlineMath math={katex_GaAs}/>).
                         </p>
                    </section>

                    {/* P-N Junction */}
                    <section>
                         <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             The P-N Junction
                         </h2>
                         <p className="leading-relaxed">
                             The heart of a semiconductor diode is the <strong className="text-teal dark:text-teal font-semibold">P-N junction</strong>, formed by joining a piece of P-type semiconductor (with excess holes) and an N-type semiconductor (with excess electrons).
                         </p>
                         <p className="mt-3 leading-relaxed">
                             When these two materials meet, a crucial process occurs at the interface:
                             <ol className="list-decimal list-inside ml-4 space-y-1 mt-2">
                                 <li><strong className="font-semibold">Diffusion:</strong> Due to concentration differences, electrons from the N-side diffuse across the junction into the P-side, and holes from the P-side diffuse into the N-side.</li>
                                 <li><strong className="font-semibold">Recombination:</strong> When diffusing electrons meet diffusing holes near the junction, they recombine, neutralizing each other.</li>
                                 <li><strong className="font-semibold">Depletion Region Formation:</strong> As electrons leave the N-side, they leave behind positively charged donor ions. As holes leave the P-side (or are filled by electrons), they leave behind negatively charged acceptor ions. This creates a narrow region around the junction that is depleted of mobile charge carriers (electrons and holes). This is called the <strong className="text-coral dark:text-gold font-semibold">depletion region</strong> or space charge region.</li>
                                 <li><strong className="font-semibold">Barrier Potential:</strong> The fixed positive and negative ions in the depletion region create an internal electric field pointing from the N-side to the P-side. This field opposes further diffusion and establishes a potential difference across the junction known as the <strong className="text-coral dark:text-gold font-semibold">barrier potential</strong> (or built-in voltage). This potential must be overcome for significant current to flow. For silicon diodes, it's approximately <InlineMath math={katex_V_barrier_Si}/>, and for germanium, about <InlineMath math={katex_V_barrier_Ge}/>.</li>
                             </ol>
                         </p>
                          {/* Diode Symbol Reference */}
                          <p className="mt-3 text-sm italic text-gray-600 dark:text-gray-400">
                             (The standard diode symbol shows an arrow pointing from the P-side (anode) to the N-side (cathode), indicating the direction of conventional current flow when forward biased. See Figure 5.5 in source material).
                          </p>
                    </section>

                    {/* Biasing */}
                    <section>
                          <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             Biasing the P-N Junction
                         </h2>
                         <p className="leading-relaxed">
                            Applying an external DC voltage across the diode is called <strong className="text-teal dark:text-teal font-semibold">biasing</strong>. This controls the diode's conductivity.
                         </p>
                          <h3 className="text-xl font-semibold font-playfair mt-4 mb-2">Forward Bias</h3>
                           <p className="leading-relaxed">
                             Occurs when the positive terminal of the external voltage source is connected to the P-side (anode) and the negative terminal to the N-side (cathode).
                           </p>
                            <ul className="list-disc list-inside ml-4 space-y-1 mt-2">
                                <li>The external voltage opposes the internal barrier potential.</li>
                                <li>Electrons (from N-side) and holes (from P-side) are pushed towards the junction.</li>
                                <li>If the external voltage exceeds the barrier potential, the depletion region narrows significantly.</li>
                                <li>The diode becomes highly conductive, allowing current to flow easily (limited mainly by external circuit resistance).</li>
                            </ul>

                          <h3 className="text-xl font-semibold font-playfair mt-4 mb-2">Reverse Bias</h3>
                          <p className="leading-relaxed">
                              Occurs when the negative terminal of the external voltage source is connected to the P-side and the positive terminal to the N-side.
                          </p>
                           <ul className="list-disc list-inside ml-4 space-y-1 mt-2">
                                <li>The external voltage adds to the internal barrier potential.</li>
                                <li>Electrons and holes are pulled away from the junction.</li>
                                <li>The depletion region widens considerably.</li>
                                <li>The diode becomes highly resistive, blocking the flow of significant current (only a very small leakage current due to minority carriers flows).</li>
                           </ul>
                             <p className="mt-3 leading-relaxed">
                               <strong className="text-coral dark:text-gold font-semibold">Zero Bias</strong> simply means no external voltage is applied. The natural barrier potential exists, but no significant current flows.
                             </p>
                     </section>

                     {/* I-V Characteristics */}
                     <section>
                          <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             Current-Voltage (<InlineMath math={katex_IV}/>) Characteristics
                         </h2>
                           <p className="leading-relaxed">
                             The relationship between the voltage applied across a diode and the current flowing through it is non-linear and shown in its <InlineMath math={katex_IV}/> curve:
                           </p>
                           <ul className="list-disc list-outside ml-6 space-y-2 mt-2">
                                <li><strong className="font-semibold">Forward Bias Region:</strong> For voltages below the <strong className="text-teal dark:text-teal">cut-in voltage</strong> (or threshold voltage, ≈0.7V for Si, ≈0.3V for Ge), the current is very small. Above the cut-in voltage, the current increases exponentially (very rapidly) with small increases in voltage. The diode essentially acts like a closed switch. A series resistor is usually needed to limit this high current.</li>
                                <li><strong className="font-semibold">Reverse Bias Region:</strong> A very small, nearly constant <strong className="text-coral dark:text-gold">leakage current</strong> (due to minority carriers) flows until the <strong className="text-coral dark:text-gold">breakdown voltage</strong> is reached.</li>
                                <li><strong className="font-semibold">Breakdown Region:</strong> If the reverse voltage exceeds the breakdown voltage, the current increases dramatically. This is usually destructive for standard diodes but is used intentionally in Zener diodes for voltage regulation.</li>
                           </ul>
                     </section>

                      {/* External Resources Mention */}
                    <section>
                         <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             Further Exploration
                         </h2>
                          <p className="leading-relaxed">
                             The video provided in the original text offers a visual explanation of these concepts. Understanding diodes is foundational for exploring more complex semiconductor devices like transistors (covered in later sections).
                          </p>
                     </section>

                </article>

                {/* Right Column */}
                 <aside className="lg:col-span-5 space-y-8 mt-8 lg:mt-0">
                     {/* Panel 1: Diode Basics Video */}
                     <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                        <YouTubeEmbed videoId="JBtEckh3L9Q" title="Video: How Semiconductor Diodes Work (P-N Junction)"/>
                     </div>

                     {/* Panel 2: Depletion Region/Barrier Potential Mini Question */}
                    <div className="bg-white dark:bg-gray-800 p-5 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <h3 className="text-xl font-semibold font-inter mb-3 text-blue-700 dark:text-blue-300">Junction Check</h3>
                         <MiniCheckQuestion
                            question="What creates the barrier potential across the P-N junction when no external voltage is applied?"
                            correctAnswer="The fixed, uncompensated positive donor ions on the N-side and negative acceptor ions on the P-side within the depletion region."
                            explanation="These fixed charges create an internal electric field that opposes further charge diffusion."
                         />
                    </div>

                     {/* Panel 3: Forward/Reverse Bias Video */}
                    <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <YouTubeEmbed videoId="FpCWKhNaSks" title="Video: Diode Forward and Reverse Biasing"/>
                     </div>

                      {/* Panel 4: Biasing Mini Question */}
                     <div className="bg-white dark:bg-gray-800 p-5 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <h3 className="text-xl font-semibold font-inter mb-3 text-green-700 dark:text-green-300">Biasing Check</h3>
                         <MiniCheckQuestion
                            question="To allow significant current flow through a silicon diode, the forward bias voltage must be approximately greater than what value?"
                            correctAnswer="0.7 Volts (the typical barrier/cut-in voltage for silicon)."
                            explanation="The external voltage needs to overcome the internal barrier potential to allow majority carriers to cross the junction easily."
                        />
                     </div>

                      {/* Panel 5: PhET Simulation (Semiconductor or CCK) */}
                     <div className="bg-white dark:bg-gray-800 p-5 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                        <h3 className="text-xl font-semibold font-inter mb-3 text-center">Explore: Diode Behavior</h3>
                        <p className="text-sm text-center mb-4 font-inter text-dark-gray dark:text-light-gray">Use the Circuit Construction Kit to build circuits with diodes and observe current flow under different bias conditions.</p>
                         <div className="relative w-full overflow-hidden aspect-video border dark:border-gray-600 rounded bg-black">
                             {/* Link to PhET CCK */}
                            <a href="https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html" target="_blank" rel="noopener noreferrer" className="absolute inset-0 flex items-center justify-center bg-gray-800 hover:bg-gray-700 transition-colors">
                                <span className="text-light-gray font-inter font-semibold p-4 text-center">Click to Open PhET: Circuit Construction Kit (DC) (New Tab)</span>
                            </a>
                        </div>
                    </div>

                     {/* Panel 6: Provided Video */}
                     <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <h3 className="text-xl font-semibold font-inter mb-3 text-purple-700 dark:text-purple-300">Additional Resource</h3>
                         <p className="text-sm mb-1 font-inter text-dark-gray dark:text-light-gray">This video provides further context:</p>
                         {/* The video link from the original text */}
                         <div className="aspect-w-16 aspect-h-9 rounded-lg overflow-hidden shadow-md">
                             <iframe
                               src="https://www.youtube.com/embed/g54vURe47gM" // Corrected embed URL
                               title="External YouTube Video on Diodes"
                               className="w-full h-full"
                               frameBorder="0"
                               allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                               allowFullScreen
                             ></iframe>
                         </div>
                     </div>

                </aside>
            </div>

             {/* Quiz Button */}
            <div className='flex justify-center items-center mt-12 lg:mt-16'>
                <button
                    onClick={() => setShowQuiz(true)}
                    className="w-full sm:w-1/2 lg:w-1/3 bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-bold font-inter py-3 px-6 rounded-lg transition-colors text-lg shadow-md"
                >
                    Test Your Diode Knowledge!
                </button>
            </div>
        </main>

        {/* Quiz Modal */}
         {showQuiz && (
            <div className="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center z-50 p-4">
              <div className="bg-off-white dark:bg-deep-navy p-6 sm:p-8 rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto relative shadow-xl border dark:border-gray-700">
                 <button onClick={resetQuiz} className="absolute top-3 right-3 text-dark-gray dark:text-light-gray hover:text-coral dark:hover:text-gold text-2xl" aria-label="Close quiz">×</button>
                 <h2 className="text-2xl font-bold font-playfair mb-6 text-center text-dark-gray dark:text-light-gray">Diodes Quiz</h2>
                 <div className="space-y-6 font-inter">
                  {quizQuestions.map((q, index) => (
                    <QuizQuestion
                      key={index}
                      // questionNumber={index + 1} // Uncomment if needed
                      question={q.question}
                      options={q.options}
                      correctAnswer={q.correctAnswer}
                      hint={q.hint}
                      selectedAnswer={selectedAnswers[index]}
                      showResults={showResults}
                      onSelectAnswer={(answerIndex: number) => handleAnswerSelect(index, answerIndex)}
                    />
                  ))}
                 </div>
                 <div className="mt-8 flex flex-col sm:flex-row justify-between items-center gap-4">
                     {!showResults ? (
                         <button onClick={handleSubmit} className="w-full sm:w-auto bg-teal hover:bg-opacity-80 dark:bg-mint dark:text-deep-navy text-white font-bold font-inter py-2 px-6 rounded transition-colors disabled:opacity-50" disabled={selectedAnswers.includes(null)}>
                             Submit Answers
                         </button>
                     ) : <div/>}
                     <button onClick={resetQuiz} className="w-full sm:w-auto bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-bold font-inter py-2 px-6 rounded transition-colors">
                         Close Quiz
                     </button>
                 </div>
                {showResults && (
                  <div className="mt-6 p-4 bg-blue-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 text-center">
                     <h3 className="text-xl font-bold font-playfair mb-2 text-dark-gray dark:text-light-gray">Quiz Results</h3>
                     <p className="text-lg font-inter text-dark-gray dark:text-light-gray">
                        You got <strong className="text-teal dark:text-mint">{score}</strong> out of <strong className="text-teal dark:text-mint">{quizQuestions.length}</strong> correct!
                     </p>
                     <p className="text-2xl font-bold font-inter mt-1 text-dark-gray dark:text-light-gray">
                         ({((score / quizQuestions.length) * 100).toFixed(0)}%)
                     </p>
                  </div>
                )}
              </div>
            </div>
        )}
    </div>
  );
}

// Assign display name
DiodesPage.displayName = 'DiodesPage';

export default DiodesPage;