'use client';

import { InlineMath, BlockMath } from 'react-katex'; // Keep imports
import { useState, ChangeEvent } from 'react'; // Removed useMemo
import QuizQuestion from '@/components/QuizQuestion'; // Assuming this component exists
import 'katex/dist/katex.min.css';

// --- Type Definitions ---
interface YouTubeEmbedProps {
  videoId: string;
  title: string;
}

interface MiniCheckQuestionProps {
  question: string;
  correctAnswer: string;
  explanation: string;
}

// !! Adjust based on your actual QuizQuestion component !!
interface QuizQuestionProps {
    key: number;
    // questionNumber?: number; // Make optional or ensure component accepts it
    question: string;
    options: string[];
    correctAnswer: number;
    hint: string;
    selectedAnswer: number | null;
    showResults: boolean;
    onSelectAnswer: (answerIndex: number) => void;
}

// --- Reusable Components (Styled as per design system) ---

// YouTube Embed Component
function YouTubeEmbed({ videoId, title }: YouTubeEmbedProps) {
  return (
    <div className="my-4">
      <p className="mb-2 font-semibold font-inter text-dark-gray dark:text-light-gray">{title}:</p>
      <div className="aspect-w-16 aspect-h-9 rounded-lg overflow-hidden shadow-md">
         <iframe
           className="w-full h-full"
           src={`https://www.youtube.com/embed/${videoId}`}
           title={title}
           frameBorder="0"
           allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
           allowFullScreen>
         </iframe>
      </div>
    </div>
  );
}

// Mini Interactive Question Component
function MiniCheckQuestion({ question, correctAnswer, explanation }: MiniCheckQuestionProps) {
  const [revealed, setRevealed] = useState(false);
  return (
    <div className="mt-6 p-4 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 shadow-md">
      <p className="font-medium text-sm mb-2 font-inter text-dark-gray dark:text-light-gray">{question}</p>
      {!revealed && (
        <button
          onClick={() => setRevealed(true)}
          className="text-xs bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-inter font-semibold py-1 px-3 rounded transition-colors"
        >
          Check Answer
        </button>
      )}
      {revealed && (
        <div className="text-sm space-y-1 font-inter">
          <p className="text-dark-gray dark:text-light-gray"><strong className="text-teal dark:text-mint">Answer:</strong> {correctAnswer}</p>
          <p className="text-dark-gray dark:text-light-gray"><strong className="text-gray-600 dark:text-gray-400">Explanation:</strong> {explanation}</p>
           <button
            onClick={() => setRevealed(false)}
            className="text-xs text-blue-600 dark:text-blue-400 hover:underline mt-1 font-inter"
          >
            Hide
          </button>
        </div>
      )}
    </div>
  );
}


// --- Page Specific Data ---
const quizQuestions = [
    // ... (quiz questions remain unchanged)
      {
    "question": "Which principle is the working foundation for reading/writing data on traditional computer hard drives?", // Clarified traditional
    "options": [
      "Electric field induction",
      "Electromagnetism (specifically magnetic fields and induction)", // More encompassing
      "Electromagnetic radiation",
      "Thermal conductivity"
    ],
    "correctAnswer": 1,
    "hint": "Hard drives use read/write heads that interact magnetically with the disk surface."
  },
  {
    "question": "In graphics tablets that use a special pen, what allows the tablet to detect the pen's position and pressure?",
    "options": [
      "Heat generated by the pen",
      "Electromagnetic induction between the pen and wire grids in the tablet", // Correct
      "Optical sensors tracking the pen tip",
      "Capacitive touch sensing like a standard tablet"
    ],
    "correctAnswer": 1,
    "hint": "The pen creates a field, inducing signals in the tablet's grid as it moves."
  },
  {
    "question": "Which common household device uses an electromagnet to repeatedly strike a gong or bell?",
    "options": [
      "Electric toothbrush",
      "Electric doorbell (traditional type)", // Correct
      "Microwave oven",
      "Toaster"
    ],
    "correctAnswer": 1,
    "hint": "The electromagnet attracts a hammer, breaking the circuit, causing it to spring back and repeat."
  },
  {
    "question": "A magnetic relay uses an electromagnet to:",
    "options": [
      "Amplify a signal",
      "Mechanically open or close contacts in a separate electrical circuit", // Correct
      "Store magnetic energy",
      "Convert AC to DC"
    ],
    "correctAnswer": 1,
    "hint": "It acts as a magnetically controlled switch, often allowing a low-power circuit to control a high-power one."
  },
  {
    "question": "What is the role of the commutator in a simple DC electric motor?",
    "options": [
      "To provide the external magnetic field",
      "To reverse the direction of current in the rotating coil every half turn", // Correct
      "To reduce friction",
      "To increase the voltage supplied to the coil"
    ],
    "correctAnswer": 1,
    "hint": "This reversal ensures the torque continues to push the coil in the same direction of rotation."
  },
  {
    "question": "An AC generator (dynamo) primarily converts:",
    "options": [
      "Electrical energy into rotational mechanical energy",
      "Rotational mechanical energy into AC electrical energy", // Correct
      "Chemical energy into AC electrical energy",
      "Light energy into AC electrical energy"
    ],
    "correctAnswer": 1,
    "hint": "It uses electromagnetic induction caused by rotating a coil in a magnetic field (or vice-versa)."
  },
  {
    "question": "Why should strong magnets be kept away from computers with traditional hard disk drives (HDDs)?",
    "options": [
      "They can overheat the processor",
      "They can interfere with the Wi-Fi signal",
      "They can potentially erase or corrupt the magnetically stored data on the disk platters", // Correct
      "They can drain the computer's battery"
    ],
    "correctAnswer": 2,
    "hint": "HDDs store data using tiny magnetic domains, which strong external fields can disrupt. (Less of an issue for SSDs)."
  },
  {
    "question": "When using an industrial electromagnet to lift heavy metal objects, what factor might *reduce* its effective lifting capacity?",
    "options": [
      "Increasing the electric current",
      "Using a larger electromagnet",
      "An air gap or non-magnetic material (like paint or dirt) between the magnet and the object", // Correct
      "Cooling the electromagnet"
    ],
    "correctAnswer": 2,
    "hint": "Air gaps significantly weaken the magnetic field strength reaching the object, reducing the magnetic force."
  }
];

// --- KaTeX Constants (if needed later) ---
// const katex_example = '...';

// --- Main Page Component ---
const ApplicationAndSafetyPage = () => { // Renamed component
  // --- State Variables ---
  const [showQuiz, setShowQuiz] = useState(false);
  const [selectedAnswers, setSelectedAnswers] = useState<(number | null)[]>(new Array(quizQuestions.length).fill(null));
  const [showResults, setShowResults] = useState(false);
  const [score, setScore] = useState(0);

  // --- Quiz Handlers ---
  const handleAnswerSelect = (questionIndex: number, answerIndex: number) => {
    if (showResults) return;
    const newSelectedAnswers = [...selectedAnswers];
    newSelectedAnswers[questionIndex] = answerIndex;
    setSelectedAnswers(newSelectedAnswers);
  };

  const handleSubmit = () => {
    const correctCount = selectedAnswers.reduce((count: number, answer: number | null, index: number) => {
      if (answer === null) return count;
      return count + (answer === quizQuestions[index].correctAnswer ? 1 : 0);
    }, 0);
    setScore(correctCount);
    setShowResults(true);
  };

  const resetQuiz = () => {
    setShowQuiz(false);
    setShowResults(false);
    setSelectedAnswers(new Array(quizQuestions.length).fill(null));
    setScore(0);
  }

  // --- Component Render ---
   return (
    <div className="bg-off-white text-dark-gray dark:bg-deep-navy dark:text-light-gray min-h-screen font-lora">
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-16 py-8">
            <h1 className="text-4xl lg:text-5xl font-bold font-playfair mb-8 lg:mb-12 text-center">
                4.7 Applications & Safety of Electromagnetism {/* Updated Title */}
            </h1>

            <div className="grid grid-cols-1 lg:grid-cols-12 lg:gap-x-12">
                {/* Left Column */}
                <article className="lg:col-span-7 space-y-6">

                    {/* Introduction */}
                    <section>
                         <p className="leading-relaxed">
                            The discoveries in electromagnetism, initially explorations of natural phenomena, have profoundly shaped modern technology. From data storage to power generation and everyday gadgets, the principles of electric and magnetic interactions are fundamental.
                         </p>
                    </section>

                    {/* Data Storage & Input */}
                    <section>
                          <h2 className="text-3xl font-semibold font-playfair mt-6 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                            Data Storage and Input Devices
                         </h2>
                         <p className="leading-relaxed">
                             Traditional computer <strong className="text-teal dark:text-teal font-semibold">hard disk drives (HDDs)</strong> rely heavily on electromagnetism. Tiny electromagnets in the read/write head are used to magnetize small sections of the disk platter, representing digital 0s and 1s. Reading the data historically involved electromagnetic induction, detecting the changes in magnetic field as the head passed over the magnetized sections (though modern techniques differ).
                         </p>
                          <p className="mt-3 leading-relaxed">
                            <strong className="text-teal dark:text-teal font-semibold">Graphics tablets</strong> (often used for digital art or signatures) utilize electromagnetic induction. The special pen generates a magnetic field. As the pen moves over the tablet surface, which contains a grid of wires, the changing magnetic field induces small voltages (emfs) in the wires below. The tablet's electronics precisely locate these induced signals, translating the pen's movement into lines on the screen.
                          </p>
                    </section>

                    {/* Common Applications */}
                    <section>
                         <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                            Everyday Electromagnetism
                         </h2>
                          <p className="leading-relaxed">
                            Electromagnets are ubiquitous in devices we use daily:
                          </p>
                           <ul className="list-disc list-outside ml-6 space-y-2 mt-2">
                                <li><strong className="font-semibold">Electric Bells/Doorbells:</strong> An electromagnet attracts a hammer to strike the bell. This movement often breaks the electromagnet's circuit, causing the hammer to spring back, re-completing the circuit and repeating the cycle.</li>
                               <li><strong className="font-semibold">Loudspeakers/Headphones:</strong> An electromagnet attached to a cone/diaphragm interacts with a permanent magnet. Varying the current through the electromagnet causes it to vibrate, moving the cone/diaphragm to create sound waves.</li>
                               <li><strong className="font-semibold">Magnetic Relays:</strong> These act as magnetically controlled switches. A low-power current energizes an electromagnet, which pulls a mechanical switch closed (or open) in a separate, often high-power, circuit. Found in cars, industrial controls, etc.</li>
                               <li><strong className="font-semibold">Electric Motors (DC):</strong> Use the force exerted by a magnetic field on a current-carrying coil to produce rotation. A <strong className="text-coral dark:text-gold">commutator</strong> reverses the current direction in the coil at the right moment to maintain continuous rotation.</li>
                               <li><strong className="font-semibold">AC Generators (Dynamos):</strong> Work on the principle of electromagnetic induction. Mechanical energy (from turbines, engines) rotates a coil within a magnetic field (or rotates a magnet near a coil), inducing an alternating emf (voltage) and thus generating AC electricity.</li>
                                <li><strong className="font-semibold">Transformers:</strong> (Covered in 4.6) Use induction to change AC voltage levels.</li>
                                <li><strong className="font-semibold">MRI Machines:</strong> Use powerful superconducting electromagnets to align atomic nuclei in the body for medical imaging.</li>
                                <li><strong className="font-semibold">Magnetic Locks & Levitation Systems:</strong> Employ strong electromagnets for securing doors or suspending objects.</li>
                           </ul>
                    </section>

                    {/* Safety */}
                     <section>
                         <h2 className="text-3xl font-semibold font-playfair mt-8 mb-4 border-b border-gray-300 dark:border-gray-700 pb-2">
                             Safety Considerations
                         </h2>
                         <p className="leading-relaxed text-red-600 dark:text-coral font-semibold">
                             While essential, strong magnetic fields and electromagnetic devices require handling with care.
                         </p>
                           <ul className="list-disc list-outside ml-6 space-y-2 mt-2">
                                <li>
                                   <strong className="font-semibold">Data Corruption:</strong> Powerful magnets brought near traditional magnetic storage media (HDDs, floppy disks, magnetic tapes) can permanently erase or corrupt the stored data. Solid State Drives (SSDs) are generally immune to this.
                                </li>
                               <li>
                                   <strong className="font-semibold">CRT Screen Distortion:</strong> Strong magnets can deflect the electron beam in old Cathode Ray Tube (CRT) televisions and monitors, causing permanent color distortion. (Not an issue for modern LCD/LED/OLED screens).
                               </li>
                               <li>
                                   <strong className="font-semibold">Medical Devices:</strong> Individuals with pacemakers or other sensitive medical implants should avoid strong magnetic fields (like those in MRI machines or large industrial magnets) as they can interfere with device operation.
                               </li>
                                <li>
                                   <strong className="font-semibold">Industrial Electromagnets:</strong> When used for lifting heavy metal objects (e.g., scrap metal), factors like the object's weight, surface condition (rust, paint), and any air gaps between the magnet and the object drastically affect the lifting capacity and must be carefully considered for safety. Dropped loads pose significant hazards.
                               </li>
                               <li>
                                   <strong className="font-semibold">High Currents/Voltages:</strong> Many electromagnetic devices involve significant electrical currents or voltages, carrying standard electrical safety risks (shock, burns, fire). Proper insulation, grounding, and operating procedures are vital.
                               </li>
                           </ul>
                     </section>

                </article>

                {/* Right Column */}
                <aside className="lg:col-span-5 space-y-8 mt-8 lg:mt-0">
                     {/* Panel 1: General Applications Video */}
                     <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                        <YouTubeEmbed videoId="O2DSgl merito" title="Video: Everyday Applications of Electromagnetism"/> {/* Placeholder ID - Find suitable video */}
                     </div>

                     {/* Panel 2: Hard Drive / Graphics Tablet */}
                     <div className="bg-white dark:bg-gray-800 p-5 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <h3 className="text-xl font-semibold font-inter mb-3 text-blue-700 dark:text-blue-300">Data & Input Tech</h3>
                         <YouTubeEmbed videoId="wtdbP1QKDic" title="Video: How Hard Drives Work (Magnetic Storage)"/>
                          <MiniCheckQuestion
                             question="What physical principle allows a graphics tablet pen (that doesn't need batteries) to interact with the tablet?"
                             correctAnswer="Electromagnetic Induction."
                             explanation="The tablet generates a field that powers the pen circuit via induction, and the pen then transmits its own field back, which is detected by the tablet grid."
                         />
                     </div>

                    {/* Panel 3: Electric Motor/Generator Video */}
                     <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <YouTubeEmbed videoId="NLdLKI9TjWI" title="Video: How Electric Motors & Generators Work (Induction)"/>
                     </div>

                     {/* Panel 4: Safety Mini Question */}
                     <div className="bg-white dark:bg-gray-800 p-5 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                           <h3 className="text-xl font-semibold font-inter mb-3 text-red-700 dark:text-coral">Safety Check</h3>
                           <MiniCheckQuestion
                              question="Is it generally safe to place a strong neodymium magnet directly on your laptop?"
                              correctAnswer="No, especially if it has a traditional Hard Disk Drive (HDD)."
                              explanation="The strong magnetic field can damage the data stored magnetically on the HDD platters. It's less risky for laptops with Solid State Drives (SSDs)."
                          />
                     </div>

                     {/* Panel 5: MRI Safety Video (Example of strong field safety) */}
                      <div className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-md border border-gray-200 dark:border-gray-700">
                         <YouTubeEmbed videoId="7MRQAJnqDxM" title="Video: MRI Safety Considerations"/>
                     </div>

                </aside>
            </div>

             {/* Quiz Button */}
            <div className='flex justify-center items-center mt-12 lg:mt-16'>
                <button
                    onClick={() => setShowQuiz(true)}
                    className="w-full sm:w-1/2 lg:w-1/3 bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-bold font-inter py-3 px-6 rounded-lg transition-colors text-lg shadow-md"
                >
                    Check Application & Safety Knowledge!
                </button>
            </div>
        </main>

         {/* Quiz Modal */}
         {showQuiz && (
             <div className="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center z-50 p-4">
              <div className="bg-off-white dark:bg-deep-navy p-6 sm:p-8 rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto relative shadow-xl border dark:border-gray-700">
                 <button onClick={resetQuiz} className="absolute top-3 right-3 text-dark-gray dark:text-light-gray hover:text-coral dark:hover:text-gold text-2xl" aria-label="Close quiz">×</button>
                 <h2 className="text-2xl font-bold font-playfair mb-6 text-center text-dark-gray dark:text-light-gray">E&M Applications & Safety Quiz</h2>
                 <div className="space-y-6 font-inter">
                  {quizQuestions.map((q, index) => (
                    <QuizQuestion
                      key={index}
                      // questionNumber={index + 1} // Uncomment if needed
                      question={q.question}
                      options={q.options}
                      correctAnswer={q.correctAnswer}
                      hint={q.hint}
                      selectedAnswer={selectedAnswers[index]}
                      showResults={showResults}
                      onSelectAnswer={(answerIndex: number) => handleAnswerSelect(index, answerIndex)}
                    />
                  ))}
                 </div>
                 <div className="mt-8 flex flex-col sm:flex-row justify-between items-center gap-4">
                     {!showResults ? (
                         <button onClick={handleSubmit} className="w-full sm:w-auto bg-teal hover:bg-opacity-80 dark:bg-mint dark:text-deep-navy text-white font-bold font-inter py-2 px-6 rounded transition-colors disabled:opacity-50" disabled={selectedAnswers.includes(null)}>
                             Submit Answers
                         </button>
                     ) : <div/>}
                     <button onClick={resetQuiz} className="w-full sm:w-auto bg-coral hover:bg-opacity-80 dark:bg-gold dark:text-deep-navy text-white font-bold font-inter py-2 px-6 rounded transition-colors">
                         Close Quiz
                     </button>
                 </div>
                {showResults && (
                  <div className="mt-6 p-4 bg-blue-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 text-center">
                     <h3 className="text-xl font-bold font-playfair mb-2 text-dark-gray dark:text-light-gray">Quiz Results</h3>
                     <p className="text-lg font-inter text-dark-gray dark:text-light-gray">
                        You got <strong className="text-teal dark:text-mint">{score}</strong> out of <strong className="text-teal dark:text-mint">{quizQuestions.length}</strong> correct!
                     </p>
                     <p className="text-2xl font-bold font-inter mt-1 text-dark-gray dark:text-light-gray">
                         ({((score / quizQuestions.length) * 100).toFixed(0)}%)
                     </p>
                  </div>
                )}
              </div>
            </div>
        )}
    </div>
  );
}

// Assign display name
ApplicationAndSafetyPage.displayName = 'ApplicationAndSafetyPage';

export default ApplicationAndSafetyPage;