name: Update User Interests Cron Job

on:
  schedule:
    # Runs daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-interests:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Cron Endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "Content-Type: application/json" \
            "$API_ENDPOINT/api/cron/update-interests")
          
          if [ "$response" -ne 200 ]; then
            echo "Cron job failed with status code: $response"
            cat response.txt
            exit 1
          fi